felix-hilden/tekore

.gitignore, spotipy/auth.py, spotipy/client/album.py, spotipy/client/artist.py, spotipy/client/base.py, spotipy/client/browse.py, spotipy/client/follow.py, spotipy/client/playlist.py, spotipy/convert.py
I also fixed some python2 style formatting with `%`
=> Usage of fstrings to fix #11

spotipy/client/base.py
Preparations for larger modifications to sending requests to the Spotify API
=> API request refactoring

spotipy/client/base.py, spotipy/client/playlist.py, spotipy/sender.py
=> Architecture overhaul

docs/advanced.rst, docs/readme/getting_started.rst, docs/reference/auth.rst, docs/reference/scope.rst, readme.rst, spotipy/auth.py, spotipy/scope.py, spotipy/util.py, tests/auth.py, tests/client/_cred.py, tests/scope.py
Updates to scopes and authentication
=> Scope update, fixes #30

spotipy/model/album/__init__.py, tests/client/album.py, tests/client/artist.py, tests/client/track.py
=> Add is_playable to SimpleAlbum, test client with markets from token

spotipy/model/local.py, spotipy/model/playlist.py, tests/client/_resources.py, tests/client/playlist.py
=> Handle local tracks in playlist

spotipy/client/album.py, spotipy/client/artist.py, spotipy/client/browse/__init__.py, spotipy/client/library.py, spotipy/client/player.py, spotipy/client/playlist/view.py, spotipy/client/track.py, tests/client/artist.py
=> Change market default to None

spotipy/model/playlist.py
=> Handle None tracks in PlaylistTrack

spotipy/model/play_history.py, tests/client/follow.py, tests/client/player.py
=> PlayHistoryCursor may be None

docs/documents/advanced_usage.rst, docs/reference/client.rst, spotipy/client/base.py, tests/client/follow.py, tests/client/paging.py, tests/client/player.py
=> Add methods to get all paging results

spotipy/client/player.py, spotipy/model/__init__.py, spotipy/model/album/__init__.py, spotipy/model/album/full.py, spotipy/model/audio_analysis.py, spotipy/model/currently_playing.py, spotipy/model/device.py, spotipy/model/member.py, spotipy/model/play_history.py, spotipy/model/playlist.py, spotipy/model/track.py, spotipy/model/user.py, tests/client/paging.py, tests/client/player.py, tests/client/playlist.py, tests/client/track.py
=> Differentiate attributes that are returned as None from ones not present

docs/documents/advanced_usage.rst, docs/reference/client.rst, docs/reference/model.rst, spotipy/auth.py, spotipy/client/__init__.py, spotipy/convert.py, spotipy/scope.py, spotipy/sender.py, spotipy/serialise.py, spotipy/util.py
Fixes #53 to provide examples of the usage of each module in its docstring.
=> Examples of usage in module documentation

docs/documents/advanced_usage.rst, docs/documents/getting_started.rst, docs/reference/client.rst, docs/reference/model.rst, spotipy/util.py, tests/util.py
=> RefreshingCredentials and refreshing client token

spotipy/__init__.py
=> Import only essentials at the top level

spotipy/util.py, tests/util.py
=> Reflect automatic refreshing in properties

docs/documents/getting_started.rst, docs/examples/play_saved_album.rst, docs/index.rst, docs/reference/client.rst, readme.rst, spotipy/client/player/__init__.py, spotipy/client/player/modify.py, spotipy/client/player/view.py, tests/client/player.py
=> Split player class and playback start

spotipy/client/track.py, tests/client/track.py
=> Allow Nones in audio features

spotipy/auth.py, spotipy/util.py, tests/util.py
=> Correctly refresh client credentials

docs/examples/auth_server.rst, spotipy/auth.py, spotipy/util.py, tests/auth.py
=> Fix user authorisation parameters

docs/documents/advanced_usage.rst, spotipy/sender.py
=> Pass session to sender

spotipy/auth.py, spotipy/util.py, tests/auth.py, tests/util.py
=> Convert is_expiring to property

docs/documents/advanced_usage.rst, docs/examples/client_configurations.rst, spotipy/auth.py, spotipy/util.py, tests/auth.py, tests/client/_cred.py, tests/util.py
=> Refactor token refreshing

setup.py
=> Fixes version support error formatting in setup.py

setup.py, spotipy/_start.py, tests/_start.py
=> Support Python 3.6

docs/documents/advanced_usage.rst, docs/reference/util.rst, spotipy/util/__init__.py, spotipy/util/config.py, spotipy/util/credentials.py, tests/util.py
=> Optionally read refresh token in config, default varnames as variables

docs/documents/advanced_usage.rst, spotipy/util/__init__.py, spotipy/util/config.py, tests/util.py
=> Write config to file

tekore/client/api/artist.py, tekore/client/api/browse/__init__.py, tekore/client/api/follow.py, tekore/client/api/library.py, tekore/client/api/personalisation.py, tekore/client/api/player/modify.py, tekore/client/api/player/view.py, tekore/client/api/playlist/modify.py, tekore/client/api/playlist/tracks.py, tekore/client/api/playlist/view.py, tekore/client/api/search.py, tekore/client/api/track.py, tekore/client/api/user.py, tekore/client/process.py
This PR will introduce decorators to all API endpoints. Possibly also introduce new methods into `process` module. **Work In Progress**, I will let you know when it is done. Tests for async flow will come in another PR if you don't mind. I suggest squashing this PR into one commit when it is done (to reduce noise in commit history)
=> WIP: Add decorators for API endpoints

docs/examples/discord_bot.rst
Hello!
Maybe this kind of basic Discord bot example could be nice addition to the docs.
=> Add small Discord bot example

docs/examples/artist_follower.rst
Uploading the script I told you from #148.
* What else can I add to the description?
* Should it use `config_from_credentials`?
* Anything you would like to improve?
=> Added artist follower example

docs/src/404.rst
=> Add 404 page for Read the Docs

docs/src/conf.py, docs/src/index.rst, docs/src/release_notes.rst, readme_pypi.rst
Move changelog from PyPI page to RTD
=> Move changelog to documentation

.coveragerc
Up test coverage requirement to _**reasonable**_ levels.
=> Require 99% test coverage

.github/workflows/environment.yml, .github/workflows/scheduled.yml
Add workflows to test multiple operating systems and Python versions, and to perform scheduled tests.
=> Workflows for environment and scheduled tests, fixes #167

docs/src/examples/discord_bot.rst
This slightly improves the Discord Bot example.
The two commits have the reasoning and explaination for the changes they do.
Related issue: *No issue*
- [*doesn't apply*] Tests written with 100% coverage
- [*doesn't apply (?)*] Documentation and changelog entry written
=> Slightly improve the Discord Bot example

docs/requirements.txt, docs/src/conf.py, docs/src/examples/auth_server.rst, setup.py
Added authenticating server example with FastAPI framework. 
Related issue: #259
=> Added FastAPI auth server example

.github/workflows/matrix.yml, .github/workflows/scheduled.yml, docs/src/release_notes.rst, setup.py
=> Support & test Python 3.10

.gitignore, docs/src/release_notes.rst, tekore/_model/chapter/__init__.py, tekore/_model/chapter/base.py, tekore/_model/chapter/full.py, tekore/_model/member.py, tests/client/audiobook.py, tests/client/chapter.py
=> Fix tests for audiobooks

docs/src/release_notes.rst, src/tekore/_convert.py, src/tekore/_model/chapter/__init__.py, src/tekore/_model/chapter/full.py, src/tekore/_model/serialise.py, tests/client/audiobook.py, tests/client/chapter.py, tests/model.py
Related issue: #286
But the tests will fail due to another error
=> Rename Chapter.restriction to restrictions
