.travis.yml, setup.py, spotipy/__init__.py, spotipy/_verify.py, tests/_verify.py
Create safety measures for cases when the package is installed or imported with an incorrect Python version as discussed in [this comment](https://github.com/felix-hilden/spotipy/issues/22#issuecomment-545291674).
=> Fail when installing or importing with wrong Python version

spotipy/client/base.py
Fixes #44. Requests [documentation](https://requests.kennethreitz.org/en/master/user/quickstart/#json-response-content) states that `ValueError` should be expected on failed JSON decoding.
=> Expect ValueError on failed JSON decoding

spotipy/client/library.py, spotipy/scope.py, tests/scope.py
Fixes #92 to remove the need to go through `Scope` when combining `scopes` and provide better addition and subtraction behaviour.
=> Improve scope module

docs/documents/advanced_usage.rst, docs/reference/auth.rst, docs/reference/client.rst, spotipy/auth.py, spotipy/client/base.py, spotipy/sender.py, spotipy/util.py, tests/auth.py, tests/client/_cred.py, tests/sender.py
Fixes #108 
Now only senders are passed to clients, and requests kwargs are passed to those senders. Default senders and kwargs can be changed.
=> Credentials senders

readme_pypi.rst, tekore/client/api/album.py, tekore/client/api/artist.py, tekore/client/api/browse/__init__.py, tekore/client/api/follow.py, tekore/client/api/library.py, tekore/client/api/personalisation.py, tekore/client/api/player/modify.py, tekore/client/api/player/view.py, tekore/client/api/playlist/modify.py, tekore/client/api/playlist/tracks.py, tekore/client/api/playlist/view.py, tekore/client/api/search.py, tekore/client/api/track.py, tekore/client/api/user.py, tekore/client/base.py, tekore/client/decor/__init__.py, tekore/client/decor/error.py, tekore/client/decor/handle.py, tekore/client/paging.py, tests/client/full.py
Fixes #145, this works but I don't like the solution. I'd like to refactor it in some way. See also [this question](https://codereview.stackexchange.com/questions/237106/refactoring-try-blocks-with-async-await) on SE Code Review.
=> Catch 404 in paging next

tekore/_client/api/search.py
Added two examples to Search API with queries that include filter fields, and added the link to the Search for an Item page in the official docs which provides more info on how to write queries.
=> Add examples to search documentation

docs/src/advanced_usage.rst, docs/src/reference/auth.rst, docs/src/release_notes.rst, tekore/__init__.py, tekore/_auth/__init__.py, tekore/_auth/expiring.py, tekore/_auth/refreshing.py, tekore/_auth/token.py, tekore/_auth/util.py, tests/auth/expiring.py, tests/auth/refreshing.py, tests/auth/util.py
Add PKCE user authorisation.
Closes #189
<strike>Tests fail currently because access tokens cannot be refreshed in the same way. The refresh token in the environment needs to be generated with the new method.</strike>
=> PKCE user authentication

docs/src/conf.py
Path gets added as PosixPath instead of string, which results in: 'PosixPath' object has no attribute 'rstrip', and leaves one unable to compile the docs.
This explicitly converts the path to a string and thus fixes the issue
=> fixes bug in conf.py

docs/src/release_notes.rst, tekore/_model/playlist.py
This commit fixes playlist owner attribute potentially being null in `Playlist.__post_init__`.
Related issue: #212 
=> Fix nullable playlist owner attribute

docs/src/release_notes.rst, tekore/_convert.py, tests/convert.py
At some point Spotify started added a ?si= parameter in URLs copied from the client. From what I can see it's a way for them to track how links are shared. 
This change is to strip that away when calling from_url().
Currently `tk.from_url("https://open.spotify.com/track/08fMRujpKhEDTanKN9l2ud?si=Fwpd3fCkSNSFp_9O2hEgbQ")` results in a `tekore.ConversionError: Invalid id: "08fMRujpKhEDTanKN9l2ud?si=Fwpd3fCkSNSFp_9O2hEgbQ"!` error.
PS: 1 test actually fails, but I don't think it's related to this change since it's related to markets. 
```
____________________________________________________________________ TestSpotifyTrack.test_tracks_with_market _____________________________________________________________________
self = …
```
=> Ignore parameters in from_url()

docs/src/release_notes.rst, tekore/_client/api/browse/__init__.py, tests/client/browse.py
Just a small docstring change to recommendations(), adding a warning about how the [endpoint](https://developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/) requires at least one of the track_ids, genres or artist_ids parameters to be defined.
=> Update docstring for recommendations()

docs/src/reference/auth.rst, docs/src/release_notes.rst, tekore/_auth/scope.py
Adds `tekore.scope.streaming` and `tekore.scope.app_remote_control` attributes. 
I didn't include them in `tekore.scope.write`, since I'm unsure if Spotify will let you complete the authorization process if you use an account without Premium.
=> Add streaming and app-remote-control scopes

docs/src/release_notes.rst, tekore/_client/full.py, tekore/_model/paging.py
Related issue: #221
This PR improves our type hints a bit once more, fixing some low-hanging fruit in Mypy errors.
=> Typing improvements

docs/src/advanced_usage.rst, docs/src/release_notes.rst, setup.py, tekore/_client/base.py, tekore/_client/full.py, tests/client/full.py
=> Make context managers async safe (#242)

tekore/_client/api/browse/__init__.py
This library is fantastic, I've been using it in my web application. Reading through the docs I came across this small typo. Hopefully I can contribute more significantly in the future.
=> Fixed typo in recommendations documentation

tox.ini
=> Ignore MissingConfigurationWarnings in tests

src/tekore/_model/serialise.py, tests/model.py
Spotify recently changed their enums to be all caps in some cases. I found them specifically in `album_type` it's `ALBUM` instead of `album`, which breaks tekore in some cases. tekore broke because it assumed that these keys were a specific case. 
The change I've implemented makes it so that when creating the tekore models, finding the AlbumType and other StrEnum objects is case insensitive. This will help future proof in case Spotify does something similar again in the future. My implementation does not modify values of the enums, just how they are stored and later indexed. If a different solution is desired, let me know.
=> Update StrEnum to be case insensitive

docs/src/release_notes.rst, src/tekore/_model/episode.py
pydantic throws a `ValidationError` when an episode with the `audio_preview_url` field set to none is returned by the Spotify API. That is because the `Episode` base class currently expects `str` instead of `Optional[str]` for this attribute.
The [Spotify API documentation](https://developer.spotify.com/documentation/web-api/reference/get-an-episode) declares the field as a nullable string.
I successfully tested the change using the following minimal example. 
I'm not sure whether or not it would be appropriate to add a check for this change, but I did not create one. It feels wrong to use hard-coded episode IDs in a check since the episodes could change or be taken down in the future...
The existent checks seem to pass just fine, though i've never worked with tox before and might have …
=> Nullable Episode.audio_preview_url

docs/src/advanced_usage.rst, docs/src/reference/client.rst, docs/src/release_notes.rst, src/tekore/__init__.py, src/tekore/_client/__init__.py, src/tekore/_client/full.py, src/tekore/_client/short_link.py, tests/client/_resources.py, tests/client/full.py, tests/client/short_link.py
=> Support short links (#301)

docs/src/release_notes.rst, src/tekore/_model/playlist.py
Changed the type the of the `images` attribute in the `Playlist` base class to a nullable list to avoid a pydantic ValidationError in cases where the API returns `null`. This happens when requesting an empty playlist without a custom image.
Related issue: none created
Some tox checks have failed in my environment, though the errors don't seem to be related to the implemented change.
I have manually tested the change by requesting an emtpy playlist using `spotify.playlist('<playlist-id>')`, which resulted in the following (shortened) traceback prior to the change:
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for FullPlaylist
images
Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]
For further information visit …
```
=> Fixed a ValidationError when requesting a Playlist without a cover image

docs/src/release_notes.rst, src/tekore/_model/album/base.py
Related issue: #318 
Ran into the same issue and the fix was simple enough. However, I'm unsure on writing a test that'll cover it for any user.  The api seems to only return this album type for top tracks (as of writing). Requesting the track or album specifically just gives the (presumably older/depreciating default) 'single' return type.
=> Added "ep" to AlbumType enum

docs/src/getting_started.rst, docs/src/release_notes.rst, src/tekore/_auth/util.py
This PR adds an `open_browser` parameter to both auth prompt functions. This is intended to behave similarly to the option in [spotipy](https://github.com/spotipy-dev/spotipy/blob/8f003147f7649e957223373b2da4deae2bcdec36/spotipy/oauth2.py#L313-L314) ([ref 2](https://github.com/spotipy-dev/spotipy/blob/8f003147f7649e957223373b2da4deae2bcdec36/spotipy/oauth2.py#L431-L440)), allowing for interactive auth without an attempt to open the system default browser.
This beneficial in some instances where opening the default browser could be abrupt to the user; I sometimes find manually pasting the link into my currently open browser helpful, as e.g. my system default browser is not open at the time, or I am using WSL, a VM, a container, etc. from which the relevant auth code is being invoked.
The …
=> Add open_browser param to auth prompts

docs/src/release_notes.rst, src/tekore/_client/api/playlist/modify.py
Uploading a cover image to a playlist needs the `ugc-image-upload` scope. This change adds this scope to required scopes of `SpotifyPlaylistModify.playlist_cover_image_upload`.
I does not look like this change needs to be covered by a test.
- [-] Tests written with 100% coverage
- [+] Documentation and changelog entry written
- [+] All `tox` checks passed with an appropriately configured
=> Add ugc_image_upload scope to playlist_cover_image_upload

docs/src/release_notes.rst, src/tekore/_model/track.py
Related issue: N/A
Apparently unplayable tracks (see https://open.spotify.com/album/72unDeCzOJ7Ho2fICTX8Kz in NL market) don't have `preview_url` attribute set. I'm not sure if this is the case for all unplayable tracks, or just these two, but `Track` needs to have a default for `preview_url` set to `None` to handle this case.
=> Allow for missing track preview_url
